#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
write_files:
  # Add newline to first motd
  - path: /etc/update-motd.d/10-uname
    content: echo ""
    append: true
    permissions: 0o755
  # Remove license info
  - path: /etc/motd
  # Write new motd
  - path: /etc/update-motd.d/90-updates
    source:
      uri: file:///boot/firmware/includes/motd_updates
    permissions: 0o755
  # Cron job to run apt-get update every 6 hours
  - path: /etc/cron.d/system-update
    permissions: 0o644
    content: |
      0 */6 * * * root apt-get update
