# shellcheck shell=bash
# Shared helpers. Sourced by install.sh, every module, and - once installed
# into the rescue system as $COMMON_LIB - by rescue/restore.sh.

set -euo pipefail

# ---------- output ----------
_c() { printf '\033[%sm%s\033[0m\n' "$1" "$2"; }
log()  { _c '1;34' "==> $*"; }
ok()   { _c '1;32' "  ok  $*"; }
skip() { _c '0;90' "  --  $*"; }
warn() { _c '1;33' "  !!  $*" >&2; }
die()  { _c '1;31' "  XX  $*" >&2; exit 1; }

confirm() {
    [[ "${HOMELAB_ASSUME_YES:-0}" == "1" ]] && return 0
    read -rp "$1 [y/N] " reply
    [[ "$reply" =~ ^[Yy]$ ]]
}

# ---------- guards ----------
need_root() { [[ $EUID -eq 0 ]] || die "must run as root"; }

need_cmd() {
    for c in "$@"; do
        command -v "$c" >/dev/null || die "missing command: $c"
    done
}

need_tryboot_support() {
    [[ -e /proc/device-tree/chosen/bootloader/tryboot ]] \
        || die "firmware does not expose tryboot (needs Pi 4/5 with current EEPROM)"
}

booted_via_tryboot() {
    local v
    v=$(od -An -tu4 --endian=big /proc/device-tree/chosen/bootloader/tryboot 2>/dev/null \
        | tr -d ' ') || return 1
    [[ "$v" == "1" ]]
}

ROLE_FILE=/etc/homelab-role
current_role() { cat "$ROLE_FILE" 2>/dev/null || echo main; }

# ---------- SD card layout ----------
# MBR, four primaries: p1 bootA, p2 rootA, p3 bootB, p4 rootB - see AGENTS.md
# for why. Do not convert to GPT: the firmware counts partition numbers
# differently there and tryboot becomes hard to reason about.
PART_BOOT_A=1
PART_ROOT_A=2
PART_BOOT_B=3
PART_ROOT_B=4

BOOT_DIR=/boot/firmware
DATA_DIR=/data

RESCUE_ROOT_MNT=/mnt/rescue
RESCUE_BOOT_MNT=/mnt/rescue-boot
MAIN_ROOT_MNT=/mnt/main
MAIN_BOOT_MNT=/mnt/main-boot

# Where the rescue system keeps its own copy of this file.
COMMON_LIB=/usr/local/lib/homelab/common.sh

# The rescue system looks for the arm marker on its own boot partition, which
# is $BOOT_DIR only from INSIDE the rescue system. The live system reaches it
# through arm_restore()/disarm_restore()/restore_armed() at the bottom.
ARM_NAME=homelab-restore.arm
ARM_MARKER="$BOOT_DIR/$ARM_NAME"

# The /data fstab line is generated by 01-data.sh and stashed here so a restore
# can put it back. It lives on the boot partition because that is reachable
# from both systems.
DATA_FSTAB_SNIPPET="$BOOT_DIR/homelab-data.fstab"

# Proves the external disk is really mounted and is really ours. Docker refuses
# to start without it, which is what stops containers initialising fresh
# databases into an empty mount point.
DATA_MARKER="$DATA_DIR/.homelab-data"

# Populates: DISK, DISK_ID, DEV_BOOT_A, DEV_ROOT_A, DEV_BOOT_B, DEV_ROOT_B.
# Works from either system - both boot off the same card.
detect_disk() {
    local root_src pk
    root_src=$(findmnt -no SOURCE /) || die "cannot determine root source"
    pk=$(lsblk -no PKNAME "$root_src" | head -1)
    [[ -n "$pk" ]] || die "cannot determine parent disk of $root_src"
    DISK="/dev/$pk"

    [[ "$(lsblk -no PTTYPE "$DISK" | head -1)" == "dos" ]] \
        || die "partition table on $DISK is not MBR - see lib/common.sh layout notes"

    DISK_ID=$(sfdisk --disk-id "$DISK" | sed 's/^0x//')

    local sep=""
    [[ "$DISK" =~ [0-9]$ ]] && sep="p"
    DEV_BOOT_A="${DISK}${sep}${PART_BOOT_A}"
    DEV_ROOT_A="${DISK}${sep}${PART_ROOT_A}"
    DEV_BOOT_B="${DISK}${sep}${PART_BOOT_B}"
    DEV_ROOT_B="${DISK}${sep}${PART_ROOT_B}"
}

partuuid_for() { printf '%s-%02d\n' "$DISK_ID" "$1"; }

# ---------- copying one system onto the other ----------
# Excluded from every rootfs copy. /data is excluded because it is a separate
# disk entirely; /boot/firmware because it is copied separately, with its own
# per-system edits.
RSYNC_EXCLUDES=(
    --exclude=/dev/*      --exclude=/proc/*  --exclude=/sys/*
    --exclude=/tmp/*      --exclude=/run/*   --exclude=/mnt/*
    --exclude=/media/*    --exclude=/lost+found
    --exclude=/data/*     --exclude=/boot/firmware/*
    --exclude=/var/swap
)

# Recreate the mount points whose contents RSYNC_EXCLUDES skipped.
make_runtime_dirs() {
    local root="$1" d
    for d in dev proc sys tmp run mnt media data boot/firmware; do
        mkdir -p "$root/$d"
    done
    chmod 1777 "$root/tmp"
}

# Rewrite a cloned system's fstab so it points at its own partitions.
# usage: retarget_fstab <fstab-path> <boot-partnum> <root-partnum>
#
# Matches on mountpoint rather than on the old UUID, so it is safe to run
# repeatedly and in either direction.
retarget_fstab() {
    local fstab="$1" bootn="$2" rootn="$3"
    local boot_uuid root_uuid
    boot_uuid="PARTUUID=$(partuuid_for "$bootn")"
    root_uuid="PARTUUID=$(partuuid_for "$rootn")"

    awk -v b="$boot_uuid" -v r="$root_uuid" '
        $2 == "/boot/firmware" { print b, $2, $3, $4, $5, $6; next }
        $2 == "/"              { print r, $2, $3, $4, $5, $6; next }
        { print }
    ' "$fstab" > "${fstab}.new" && mv "${fstab}.new" "$fstab"
}

# Point a boot partition's cmdline.txt at a given root partition.
set_cmdline_root() {
    local cmdline="$1" rootn="$2"
    sed -i "s|root=PARTUUID=[^[:space:]]*|root=PARTUUID=$(partuuid_for "$rootn")|" "$cmdline"
    # First-boot machinery must never fire again on either system.
    sed -i 's|init=/usr/lib/raspberrypi-sys-mods/firstboot||g; s|systemd\.run[^[:space:]]*||g' \
        "$cmdline"
}

# Both places a hostname lives. Skipping /etc/hosts leaves every sudo on the
# renamed system stalling on a failed lookup.
set_system_hostname() {
    local root="$1" name="$2"
    echo "$name" > "$root/etc/hostname"
    sed -i "s|^\(127\.0\.1\.1[[:space:]]\+\).*|\1$name|" "$root/etc/hosts"
}

# Everything that turns a plain clone at $RESCUE_ROOT_MNT into the rescue
# system. Run after every rootfs sync, by 05-rescue.sh (first clone) and by
# homelab-checkpoint (each refresh). rescue/restore.sh undoes exactly this
# list - the two must be read as a pair.
finalise_rescue_system() {
    : "${REPO_DIR:?}"

    retarget_fstab "$RESCUE_ROOT_MNT/etc/fstab" "$PART_BOOT_B" "$PART_ROOT_B"
    # The rescue system has no business touching the data disk.
    sed -i "\|[[:space:]]${DATA_DIR}[[:space:]]|d" "$RESCUE_ROOT_MNT/etc/fstab"

    echo rescue > "$RESCUE_ROOT_MNT$ROLE_FILE"
    set_system_hostname "$RESCUE_ROOT_MNT" "rescue-$(hostname)"

    # It exists to copy files, not to run the stack.
    ln -sf /dev/null "$RESCUE_ROOT_MNT/etc/systemd/system/docker.service"
    ln -sf /dev/null "$RESCUE_ROOT_MNT/etc/systemd/system/docker.socket"

    install -Dm755 "$REPO_DIR/rescue/restore.sh" \
        "$RESCUE_ROOT_MNT/usr/local/sbin/homelab-restore"
    install -Dm644 "$REPO_DIR/lib/common.sh" "$RESCUE_ROOT_MNT$COMMON_LIB"
    install -Dm644 "$REPO_DIR/rescue/homelab-restore.service" \
        "$RESCUE_ROOT_MNT/etc/systemd/system/homelab-restore.service"
    mkdir -p "$RESCUE_ROOT_MNT/etc/systemd/system/multi-user.target.wants"
    ln -sfn /etc/systemd/system/homelab-restore.service \
        "$RESCUE_ROOT_MNT/etc/systemd/system/multi-user.target.wants/homelab-restore.service"
}

# ---------- arming the restore, from the live system ----------
# Returns 1 rather than dying when there is no rescue boot partition yet, so
# homelab-status can still report on a half-provisioned card.
_with_rescue_boot() {
    local action="$1" mounted=0 rc=0
    [[ -b "${DEV_BOOT_B:?run detect_disk first}" ]] || return 1

    mkdir -p "$RESCUE_BOOT_MNT"
    if mountpoint -q "$RESCUE_BOOT_MNT"; then
        mounted=1
    else
        local opts=()
        [[ "$action" == check ]] && opts=(-o ro)
        mount "${opts[@]}" "$DEV_BOOT_B" "$RESCUE_BOOT_MNT" \
            || die "cannot mount rescue boot partition"
    fi

    local marker="$RESCUE_BOOT_MNT/$ARM_NAME"
    case "$action" in
        arm)    touch "$marker"; sync ;;
        disarm) rm -f "$marker"; sync ;;
        check)  [[ -f "$marker" ]] || rc=1 ;;
    esac

    (( mounted )) || umount "$RESCUE_BOOT_MNT"
    return "$rc"
}

arm_restore()    { _with_rescue_boot arm; }
disarm_restore() { _with_rescue_boot disarm; }
restore_armed()  { _with_rescue_boot check; }
